name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag or commit SHA
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${GITHUB_SHA::7}"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Determined image tag: $TAG"

      - name: Build Docker image
        run: docker build -t whooot-studio/client:latest -t whooot-studio/client:${{ env.IMAGE_TAG }} .

      - name: Build Docker image
        run: docker build -t whooot-studio/client:${{ env.IMAGE_TAG }} -t whooot-studio/client:latest .

      - name: Save Docker image to artifact
        run: docker save whooot-studio/client:${{ env.IMAGE_TAG }} whooot-studio/client:latest -o client.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: client.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          docker tag whooot-studio/client:${{ env.IMAGE_TAG }} ghcr.io/whooot-studio/client:${{ env.IMAGE_TAG }}
          docker tag whooot-studio/client:latest ghcr.io/whooot-studio/client:latest
          docker push ghcr.io/whooot-studio/client:${{ env.IMAGE_TAG }}
          docker push ghcr.io/whooot-studio/client:latest
